In [27]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from tqdm import tqdm
from datetime import datetime

In [28]:
COOKIE = "PEGA_AQUI_TU_COOKIE"

HEADERS = {
    "User-Agent": "Mozilla/5.0",
    "Cookie": "remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IndnWXRsbTVpT3VEd3hlQ1NRNzVmTmc9PSIsInZhbHVlIjoiVHIwMkV3cmRvOHg4WDIrNC9wQnh3cVdrWmExazFvTTY2R080Tk8vMzFLZ3ZOWWdtLzZtenFzcC9qbU44U2QwNW1kZy9iVDNabCs5bGJENDlmR05tQlpkNmxyK3hXR1lIcXFWZitMVnEza1Jsb1Y2RHRuZmpnd281NmllOWJrRTVxdnJFRXl6Y1BUV1YxWmltM0RrUTlSekViY05vVUNpd25HNUY2WXFkbkxGZnZmc2RqQ3htUnEyQnI5cTNzbm96aXY5ZVZjOWVMcGJTRnZEK0NaSkp1SmNKK1hINEpyVW5kVmxaNlN0Zk0rYz0iLCJtYWMiOiJmOWRlM2I3MDVlZDRkZDQxMGNkMTM1ZTRiZjk5MjkyZjQ4ZDNjYjZmMGFkZjI3ZWUyZTRhYTZhNDAyMjIyYWMwIn0%3D; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6ImY3eElTaEVqWGRXYXJDUld5WW5DbFE9PSIsInZhbHVlIjoiNWRYcFdPUkJ3aERxRWEyMHN4aG16eU1ld2YzYXJvN3IrNkZhaVc3Y2J1WUhKREhoMnJNV1lQZjBhRXZobW5NTjl6RjFpSjd0OEtZbFhscFBjYk9SSzBrSndEK0dzSHNTd3RMTUxuWW9QWEM2Y0E4eXJjdVRoWHBNUXlJQlhCbURzNWtYaTYvL0gzVnpOeUd6aGhFbU1rVTBwUU9UL1Y1UWtPS25kNzRBYXM4eVpVSHYrQXFlTm9BaTlhNUU2K0QxT29MMkt1YWpGSUxhMWxxZWlTdGRtc2hzTnNJU2w3NEhIWFMreWdlNWUzdz0iLCJtYWMiOiI3Y2IwNzYwODIwOWZmOWUyYTgzMTZjNDk5NWNhMjRkMjYxNmZjMzNmYWUxY2FiNThjMGI0ZTNhZDU3YWExYjg5In0%3D; _ga=GA1.1.626560028.1768378357; FCCDCF=%5Bnull%2Cnull%2Cnull%2C%5B%22CQeBJ0AQeBJ0AEsACBESCNFoAP_gAEPgAAiQK1IB_C7EbCFCiDJ3IKMEMAhHABBAYsAwAAYBAwAADBIQIAQCgkEYBASAFCACCAAAKASBAAAgCAAAAUAAIAAFAABAAAwAIBAIIAAAgAAAAEAIAAAACIAAEQCAAAAEAEAAkAgAAAIASAAAAAAAAACBAAAAAAAAAAAAAAAABAAAAQAAQAAAAAAAiAAAAAAAABAIAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAABAAAAAAAQR2QD-F2I2EKFEGCuQUYIYBCuACAAxYBgAAwCBgAAGCQgQAgFJIIkCAEAIEAAEAAAQAgCAABQEBAAAIAAAAAqAACAABgAQCAQAIABAAAAgIAAAAAAEQAAIgEAAAAIAIABABAAAAQAkAAAAAAAAAECAAAAAAAAAAAAAAAAAAAAAEABgAAAAAABEAAAAAAAACAQIAAA.IK1IB_C7EbCFCiDJ3IKMEMAhXABBAYsAwAAYBAwAADBIQIAQCkkEaBASAFCACCAAAKASBAAAoCAgAAUAAIAAVAABAAAwAIBAIIEAAgAAAQEAIAAAACIAAEQCAAAAEAEAAkAgAAAIASAAAAAAAAACBAAAAAAAAAAAAAAAABAAAASAAwAAAAAAAiAAAAAAAABAIEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAABAAAAAAAQ%22%2C%222~61.89.122.161.184.196.230.314.442.445.494.550.576.827.1029.1033.1046.1047.1051.1097.1126.1166.1301.1342.1415.1725.1765.1942.1958.1987.2068.2072.2074.2107.2213.2219.2223.2224.2328.2331.2387.2416.2501.2567.2568.2575.2657.2686.2778.2869.2878.2908.2920.2963.3005.3023.3100.3126.3219.3234.3235.3253.3309.3731.6931.8931.13731.15731.33931~dv.%22%2C%22C560B371-107E-4111-BF0D-81081B5B4CE6%22%5D%2Cnull%2Cnull%2C%5B%5B32%2C%22%5B%5C%220210bd97-ad63-4d8e-889c-2b6fd8ee309b%5C%22%2C%5B1768378357%2C125000000%5D%5D%22%5D%5D%5D; _ga_KSK91ZXWE3=GS2.1.s1772912173$o80$g1$t1772915241$j60$l0$h0; FCNEC=%5B%5B%22AKsRol-8ckc5Be9Ie45PLFGbUfbOaNAUmPofIxzMdcTzD__HnnXF9c25AIpIA2eIVS2OdtAa4fSI_PZdxV4-FAhGpBJcTl9iiJ30KRRJch4ghhdaldf9eyGKhNmdlYOW1QqSVzTK72tac6jEtCA4PmeyBwSRy_s7IQ%3D%3D%22%5D%5D; XSRF-TOKEN=eyJpdiI6InBnY3lLQ0ZXa0hXOWJUTHdFc252TVE9PSIsInZhbHVlIjoidWlJQWF5Vldob1BDclhxRmV5MkIwd0xKb0MyUXlwcm15ZkVGUW1abXRCNVNNMGlIeldUTCtVL1VNbG1kak8xeXp3Q1g0citrdTdONkh2TDVDMExxbm13dU5IMWFMcmtYeDZQci8yK1dCWDNGT3cvMm5qR3gvQXJPb09PUGxIa1kiLCJtYWMiOiJhMTk1ZGMyZjc5MDk3NWUyOWFhYzJjYjgwYTdkNmJjNjI5NzJiMDE1MDBkOTlkN2QyNmJhYjBlYTc5MWE0ZjcwIn0%3D; sbbl_session=eyJpdiI6Ik9ZQXlrVmc2aUt5cHZON1hmUmR0Wmc9PSIsInZhbHVlIjoiUkFVY28zTjE1Qmp6bitHSUFnMXEwUzRvTVppQm1zaEtzVGpDVHdwQ1FTS0dkeUpvU3pObFZHdmpFQkJoZmJkZUtSVjdPRzBydkFzbVZ6Rmt4bFlDVGFZVTMrUWZ6TzFneS9wWnhwcTNoSWVTRXAzdkR3YTJQVDZzOE9aaitKWlQiLCJtYWMiOiIzOWM4Njg1MDU4NDMwNDIyMmM2ODAxYmQ5NzdmNzBiNTk3NGZkZWM1N2RjODU3YTY4N2JhNmM4NmE4N2ZjODY4In0%3D"
}

START_TEAM = 1
END_TEAM = 200
DELAY = 0.1

In [29]:
session = requests.Session()
session.headers.update(HEADERS)

data = []

for team_id in tqdm(range(START_TEAM, END_TEAM)):

    url = f"https://sbbl.es/equipos/{team_id}"
    response = session.get(url)

    if response.status_code != 200:
        continue

    soup = BeautifulSoup(response.text, "html.parser")

    team_name_tag = soup.select_one("h1")
    team_name = team_name_tag.text.strip() if team_name_tag else f"team_{team_id}"

    players = soup.select(".agent-name")

    for p in players:
        data.append({
            "team_id": team_id,
            "team": team_name,
            "player": p.text.strip()
        })

    time.sleep(DELAY)

df = pd.DataFrame(data)

df

100%|██████████| 199/199 [01:30<00:00,  2.20it/s]

     team_id               team          player
0          5  Mandarina Cowboys          Mystic
1          6    TEAM DAI-GURREN  AsterTheNugget
2          6    TEAM DAI-GURREN       Visan ._.
3          6    TEAM DAI-GURREN          Ismael
4          7         Team Skull            Jaim
..       ...                ...             ...
328      197    Meta•L Breakers            koke
329      197    Meta•L Breakers         Nórdico
330      197    Meta•L Breakers         Pedruck
331      197    Meta•L Breakers        _McAran_
332      197    Meta•L Breakers        MultiFER

[333 rows x 3 columns]

In [31]:
df.to_csv("sbbl_players.csv", index=False)
print("Dataset guardado")

In [32]:
def detectar_equipos(lista_jugadores, df, min_jugadores=3):

    jugadores = [j.lower() for j in lista_jugadores]

    df_temp = df.copy()
    df_temp["player_lower"] = df_temp["player"].str.lower()

    coincidencias = df_temp[df_temp["player_lower"].isin(jugadores)]

    resultado = (
        coincidencias
        .groupby("team")
        .agg(
            jugadores_encontrados=("player", list),
            total=("player", "count")
        )
        .reset_index()
    )

    resultado = resultado[resultado["total"] >= min_jugadores]

    return resultado.sort_values("total", ascending=False)

In [33]:
lista = [
    "Sesiomaru",
    "Fujen",
    "LarkinX",
    "Char_218",
    "OtroJugador"
]

detectar_equipos(lista, df)

              team        jugadores_encontrados  total
0  Team Windmill X  [Sesiomaru, Fujen, LarkinX]      3

In [43]:
from datetime import datetime

with open("last_update.txt", "w") as f:
    f.write(datetime.now().strftime("%d %b %Y %H:%M"))